# This file generates the GitHub Actions matrix.
---
include:
  - board: seeeduino_xiao_ble
    shield: lism_right rgbled_adapter
    artifact-name: lism_right_peripheral_trackball
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: seeeduino_xiao_ble
    shield: lism_left rgbled_adapter
    artifact-name: lism_left_peripheral_trackball
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  

  - board: seeeduino_xiao_ble
    shield: lism_dongle rgbled_adapter
    artifact-name: lism_dongle_central_trackball
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
  # Reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset-seeeduino_xiao_ble-zmk
